language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -q -e . --use-mirrors
script:
  - python setup.py test
  - python manage.py test
deploy:
  provider: openshift
  user: nemesiscodex@gmail.com
  password:
    secure: Nluqyv4/IdgTdlCof8QRXkj1JJg2oqVNBXCwUztxjBe7LrmkzEqBy98+yL0zvvvyqitR+059e2wGDohWhO5GDm+ACc3wMDgYlHwqLS0YAImPDZxs2fMc6PNeOYroeFNEnn9vW/HS8rHGooXMR03im6KnEtOuESP+oe4bJ7mTJ6Q=
  app: mecmapi
  domain: 'nemesiscodex'
  on:
    repo: nemesiscodex/openfonacide
